### ISSUE TITLE
Broken on Python 3.12

### ISSUE THREAD

**Issue by tobim** [wasmerio/wasmer-python#778]
Thanks for the bug report!

### Describe the bug

Trying to build fails with:
```
error[E0425]: cannot find function, tuple struct or tuple variant `PyUnicode_READY` in module `ffi`
   --> /build/wasmer-compiler-singlepass-1.1.1-vendor.tar.gz/pyo3/src/types/string.rs:234:30
    |
234 |             let ready = ffi::PyUnicode_READY(ptr);
    |                              ^^^^^^^^^^^^^^^ help: a function with a similar name exists: `PyUnicode_IS_READY`
```

Looks like an outdated pyo3 version.

### Steps to reproduce

With Nix:
`nix -L build github:nixos/nixpkgs/fcd0c62f9e11f3ce754e7e20de08531d7ac5f757#python312Packages.wasmer`

**Comment by wycontir** [comment]
this error is still happening on the latest version of both pyo3 and python. are there any possible fixes?

**Comment by woshishabii** [comment]
~~update needed~~
nvm google's first result to tutorial is out of date

**Comment by attilaolah** [comment]
Turns out these crates no longer build with `pyo3 = 0.14`, nor 0.15, nor the latest 0.26 version.

However, they do build with pyo3 0.16, albeit with warnings.

There are a set of dependabot PRs like this one, https://github.com/wasmerio/wasmer-python/pull/736, which bump the pyo3 dependency to 0.19 but that won't build either since that contains breaking changes already.

Ideally someone should update to the newest CPython API, but barring that, a workaround might be simply updating the dependency to 0.16 to get these crates to at least build.
